services:
  pyspark:
    image: jupyter/all-spark-notebook
    volumes:
      - ./spark:/home/jovyan
    ports:
      - 8888:8888
      - 4040:4040
    environment:
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/home/jovyan/spark-logs